ALTER TABLE public.players
ADD COLUMN IF NOT EXISTS gifts INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS ton_value NUMERIC(10, 2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS color TEXT DEFAULT '#CCCCCC',
ADD COLUMN IF NOT EXISTS percentage NUMERIC(5, 2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS is_participant BOOLEAN DEFAULT FALSE;
